version: '3.9'

services:
  app:
    build: 
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

      

  proxy:
    build: 
      context: ./proxy
    restart: always
    volumes:
    - static-data:/vol/static
    ports:
      - "80:8000"
      - "443:443"
    depends_on:
      - app

volumes:
  postgres-data:
  static-data: